ALTER TABLE USR_ACCOUNT
    ADD COLUMN email_verified_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '邮箱已验证标记' AFTER email_text;

ALTER TABLE USR_ACCOUNT
    ADD CONSTRAINT AK_USR_ACCOUNT_2 UNIQUE (email_text);

ALTER TABLE OAU_LOGIN
    ADD COLUMN login_scene VARCHAR(32) NOT NULL DEFAULT 'LOGIN' COMMENT '登录场景' AFTER login_status;

ALTER TABLE OAU_LOGIN
    ADD COLUMN initiator_user_id BIGINT NULL COMMENT '发起绑定的用户ID' AFTER user_id;

ALTER TABLE OAU_LOGIN
    ADD KEY IX_OAU_LOGIN_2 (provider_type, login_scene, create_time);

