CREATE TABLE IF NOT EXISTS CTN_LA_WHITEBOARD (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'CTN_LA_WHITEBOARD.id 自增长ID',
    user_id BIGINT NOT NULL COMMENT 'CTN_LA_WHITEBOARD.user_id 用户ID',
    title_text VARCHAR(200) NOT NULL COMMENT 'CTN_LA_WHITEBOARD.title_text 画板标题',
    board_kind_code VARCHAR(32) NOT NULL DEFAULT 'DRAWING' COMMENT 'CTN_LA_WHITEBOARD.board_kind_code 画板类型',
    document_json LONGTEXT NOT NULL COMMENT 'CTN_LA_WHITEBOARD.document_json 画板文档JSON',
    thumbnail_asset_id BIGINT NULL COMMENT 'CTN_LA_WHITEBOARD.thumbnail_asset_id 缩略图资产ID',
    sort_num INT NOT NULL DEFAULT 0 COMMENT 'CTN_LA_WHITEBOARD.sort_num 排序值',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CTN_LA_WHITEBOARD.create_time 创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'CTN_LA_WHITEBOARD.update_time 更新时间',
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'CTN_LA_WHITEBOARD.deleted_flag 删除标记',
    version_num INT NOT NULL DEFAULT 0 COMMENT 'CTN_LA_WHITEBOARD.version_num 版本号',
    CONSTRAINT PK_CTN_LA_WHITEBOARD PRIMARY KEY (id),
    KEY IX_CTN_LA_WHITEBOARD_1 (user_id, sort_num, update_time),
    KEY IX_CTN_LA_WHITEBOARD_2 (user_id, board_kind_code)
);
