ALTER TABLE CTN_POST
    ADD COLUMN IF NOT EXISTS status_code VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
    ADD COLUMN IF NOT EXISTS category_code VARCHAR(64) NOT NULL DEFAULT 'general',
    ADD COLUMN IF NOT EXISTS slug_code VARCHAR(128) NULL,
    ADD COLUMN IF NOT EXISTS md_bucket_name VARCHAR(128) NULL,
    ADD COLUMN IF NOT EXISTS md_object_key VARCHAR(512) NULL,
    ADD COLUMN IF NOT EXISTS word_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS line_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS reading_minutes INT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS published_time DATETIME NULL;

SET @idx_exists = (
    SELECT COUNT(1)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'CTN_POST'
      AND index_name = 'AK_CTN_POST_2'
);
SET @ddl = IF(@idx_exists = 0, 'ALTER TABLE CTN_POST ADD UNIQUE INDEX AK_CTN_POST_2 (slug_code)', 'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @idx_exists = (
    SELECT COUNT(1)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'CTN_POST'
      AND index_name = 'IX_CTN_POST_3'
);
SET @ddl = IF(@idx_exists = 0, 'ALTER TABLE CTN_POST ADD INDEX IX_CTN_POST_3 (status_code)', 'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @idx_exists = (
    SELECT COUNT(1)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'CTN_POST'
      AND index_name = 'IX_CTN_POST_4'
);
SET @ddl = IF(@idx_exists = 0, 'ALTER TABLE CTN_POST ADD INDEX IX_CTN_POST_4 (category_code)', 'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @idx_exists = (
    SELECT COUNT(1)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND table_name = 'CTN_POST'
      AND index_name = 'IX_CTN_POST_5'
);
SET @ddl = IF(@idx_exists = 0, 'ALTER TABLE CTN_POST ADD INDEX IX_CTN_POST_5 (published_time)', 'SELECT 1');
PREPARE stmt FROM @ddl;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

CREATE TABLE IF NOT EXISTS CTN_POST_TAG (
    id BIGINT NOT NULL AUTO_INCREMENT,
    post_id BIGINT NOT NULL,
    tag_code VARCHAR(64) NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    version_num INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_CTN_POST_TAG PRIMARY KEY (id),
    CONSTRAINT AK_CTN_POST_TAG_1 UNIQUE (post_id, tag_code),
    KEY IX_CTN_POST_TAG_1 (post_id),
    KEY IX_CTN_POST_TAG_2 (tag_code),
    CONSTRAINT FK_CTN_POST_TAG_1 FOREIGN KEY (post_id) REFERENCES CTN_POST(id)
);

CREATE TABLE IF NOT EXISTS CTN_POST_CATEGORY_POLICY (
    id BIGINT NOT NULL AUTO_INCREMENT,
    category_code VARCHAR(64) NOT NULL,
    enabled_flag TINYINT(1) NOT NULL DEFAULT 1,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    version_num INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_CTN_POST_CATEGORY_POLICY PRIMARY KEY (id),
    CONSTRAINT AK_CTN_POST_CATEGORY_POLICY_1 UNIQUE (category_code)
);

CREATE TABLE IF NOT EXISTS CTN_POST_CATEGORY_POLICY_GROUP (
    id BIGINT NOT NULL AUTO_INCREMENT,
    category_code VARCHAR(64) NOT NULL,
    group_code VARCHAR(32) NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0,
    version_num INT NOT NULL DEFAULT 0,
    CONSTRAINT PK_CTN_POST_CATEGORY_POLICY_GROUP PRIMARY KEY (id),
    CONSTRAINT AK_CTN_POST_CATEGORY_POLICY_GROUP_1 UNIQUE (category_code, group_code),
    KEY IX_CTN_POST_CATEGORY_POLICY_GROUP_1 (category_code),
    KEY IX_CTN_POST_CATEGORY_POLICY_GROUP_2 (group_code),
    CONSTRAINT FK_CTN_POST_CATEGORY_POLICY_GROUP_1
        FOREIGN KEY (category_code) REFERENCES CTN_POST_CATEGORY_POLICY(category_code)
);

INSERT INTO CTN_POST_CATEGORY_POLICY (category_code, enabled_flag)
VALUES ('game', 1)
ON DUPLICATE KEY UPDATE enabled_flag = VALUES(enabled_flag), update_time = CURRENT_TIMESTAMP;

INSERT INTO CTN_POST_CATEGORY_POLICY_GROUP (category_code, group_code)
VALUES ('game', 'USER'), ('game', 'FRIEND'), ('game', 'ADMIN')
ON DUPLICATE KEY UPDATE update_time = CURRENT_TIMESTAMP;
