CREATE TABLE IF NOT EXISTS MDA_USER_MUSIC_PLAYLIST (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'MDA_USER_MUSIC_PLAYLIST.id 自增长ID',
    playlist_code VARCHAR(64) NOT NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST.playlist_code 歌单业务编码',
    user_id BIGINT NOT NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST.user_id 用户ID',
    playlist_type VARCHAR(32) NOT NULL DEFAULT 'CUSTOM' COMMENT 'MDA_USER_MUSIC_PLAYLIST.playlist_type 歌单类型(DEFAULT/LIKED/CUSTOM)',
    name_text VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'MDA_USER_MUSIC_PLAYLIST.name_text 歌单名称',
    description_text VARCHAR(1024) NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST.description_text 歌单简介',
    cover_url VARCHAR(1024) NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST.cover_url 歌单封面',
    public_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'MDA_USER_MUSIC_PLAYLIST.public_flag 是否公开',
    system_reserved_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'MDA_USER_MUSIC_PLAYLIST.system_reserved_flag 是否系统保留歌单',
    sort_num INT NOT NULL DEFAULT 0 COMMENT 'MDA_USER_MUSIC_PLAYLIST.sort_num 排序值',
    metadata_json JSON NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST.metadata_json 扩展元数据',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'MDA_USER_MUSIC_PLAYLIST.create_time 创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MDA_USER_MUSIC_PLAYLIST.update_time 更新时间',
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'MDA_USER_MUSIC_PLAYLIST.deleted_flag 删除标记',
    version_num INT NOT NULL DEFAULT 0 COMMENT 'MDA_USER_MUSIC_PLAYLIST.version_num 版本号',
    CONSTRAINT PK_MDA_USER_MUSIC_PLAYLIST PRIMARY KEY (id),
    CONSTRAINT AK_MDA_USER_MUSIC_PLAYLIST_1 UNIQUE (playlist_code),
    KEY IX_MDA_USER_MUSIC_PLAYLIST_1 (user_id, playlist_type, sort_num),
    KEY IX_MDA_USER_MUSIC_PLAYLIST_2 (public_flag, sort_num)
) COMMENT='用户音乐歌单表';

CREATE TABLE IF NOT EXISTS MDA_USER_MUSIC_PLAYLIST_TRACK (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.id 自增长ID',
    playlist_code VARCHAR(64) NOT NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.playlist_code 歌单业务编码',
    provider_code VARCHAR(64) NOT NULL DEFAULT 'local' COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.provider_code provider编码',
    track_id VARCHAR(128) NOT NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.track_id 曲目业务ID',
    title_text VARCHAR(256) NOT NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.title_text 曲目标题',
    artist_text VARCHAR(256) NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.artist_text 艺术家',
    cover_url VARCHAR(1024) NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.cover_url 封面URL',
    audio_url VARCHAR(1024) NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.audio_url 音频URL',
    lyric_url VARCHAR(1024) NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.lyric_url 歌词URL',
    sort_num INT NOT NULL DEFAULT 0 COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.sort_num 排序号',
    enabled_flag TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.enabled_flag 是否启用',
    metadata_json JSON NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.metadata_json 扩展字段',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.create_time 创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.update_time 更新时间',
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.deleted_flag 删除标记',
    version_num INT NOT NULL DEFAULT 0 COMMENT 'MDA_USER_MUSIC_PLAYLIST_TRACK.version_num 版本号',
    CONSTRAINT PK_MDA_USER_MUSIC_PLAYLIST_TRACK PRIMARY KEY (id),
    CONSTRAINT AK_MDA_USER_MUSIC_PLAYLIST_TRACK_1 UNIQUE (playlist_code, provider_code, track_id),
    KEY IX_MDA_USER_MUSIC_PLAYLIST_TRACK_1 (playlist_code, enabled_flag, sort_num)
) COMMENT='用户歌单曲目表';

CREATE TABLE IF NOT EXISTS MDA_USER_MUSIC_PLAYLIST_COLLECT (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'MDA_USER_MUSIC_PLAYLIST_COLLECT.id 自增长ID',
    user_id BIGINT NOT NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST_COLLECT.user_id 用户ID',
    playlist_code VARCHAR(64) NOT NULL COMMENT 'MDA_USER_MUSIC_PLAYLIST_COLLECT.playlist_code 歌单业务编码',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'MDA_USER_MUSIC_PLAYLIST_COLLECT.create_time 创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MDA_USER_MUSIC_PLAYLIST_COLLECT.update_time 更新时间',
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'MDA_USER_MUSIC_PLAYLIST_COLLECT.deleted_flag 删除标记',
    version_num INT NOT NULL DEFAULT 0 COMMENT 'MDA_USER_MUSIC_PLAYLIST_COLLECT.version_num 版本号',
    CONSTRAINT PK_MDA_USER_MUSIC_PLAYLIST_COLLECT PRIMARY KEY (id),
    CONSTRAINT AK_MDA_USER_MUSIC_PLAYLIST_COLLECT_1 UNIQUE (user_id, playlist_code),
    KEY IX_MDA_USER_MUSIC_PLAYLIST_COLLECT_1 (playlist_code)
) COMMENT='用户收藏歌单关系表';
