ALTER TABLE MDA_MUSIC_TRACK_CACHE
    ADD COLUMN last_listen_time DATETIME NULL COMMENT 'MDA_MUSIC_TRACK_CACHE.last_listen_time 最近收听时间' AFTER source_url;

ALTER TABLE MDA_MUSIC_TRACK_CACHE
    ADD KEY IX_MDA_MUSIC_TRACK_CACHE_LISTEN_TIME (last_listen_time);
