ALTER TABLE CTN_POST
    ADD COLUMN IF NOT EXISTS status_code VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED' COMMENT 'CTN_POST.status_code 文章状态',
    ADD COLUMN IF NOT EXISTS category_code VARCHAR(64) NOT NULL DEFAULT 'general' COMMENT 'CTN_POST.category_code 分类编码',
    ADD COLUMN IF NOT EXISTS slug_code VARCHAR(128) NULL COMMENT 'CTN_POST.slug_code 文章短链编码',
    ADD COLUMN IF NOT EXISTS md_bucket_name VARCHAR(128) NULL COMMENT 'CTN_POST.md_bucket_name markdown存储bucket',
    ADD COLUMN IF NOT EXISTS md_object_key VARCHAR(512) NULL COMMENT 'CTN_POST.md_object_key markdown存储key',
    ADD COLUMN IF NOT EXISTS word_count BIGINT NOT NULL DEFAULT 0 COMMENT 'CTN_POST.word_count 字数',
    ADD COLUMN IF NOT EXISTS line_count BIGINT NOT NULL DEFAULT 0 COMMENT 'CTN_POST.line_count 行数',
    ADD COLUMN IF NOT EXISTS reading_minutes INT NOT NULL DEFAULT 1 COMMENT 'CTN_POST.reading_minutes 阅读分钟数',
    ADD COLUMN IF NOT EXISTS published_time DATETIME NULL COMMENT 'CTN_POST.published_time 发布时间';

ALTER TABLE CTN_POST
    ADD UNIQUE INDEX IF NOT EXISTS AK_CTN_POST_2 (slug_code),
    ADD INDEX IF NOT EXISTS IX_CTN_POST_3 (status_code),
    ADD INDEX IF NOT EXISTS IX_CTN_POST_4 (category_code),
    ADD INDEX IF NOT EXISTS IX_CTN_POST_5 (published_time);

UPDATE CTN_POST
SET status_code = 'PUBLISHED',
    category_code = COALESCE(NULLIF(category_code, ''), 'general'),
    published_time = COALESCE(published_time, create_time)
WHERE status_code IS NULL OR status_code = '' OR published_time IS NULL;

CREATE TABLE IF NOT EXISTS CTN_POST_TAG (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'CTN_POST_TAG.id 自增长ID',
    post_id BIGINT NOT NULL COMMENT 'CTN_POST_TAG.post_id 帖子ID',
    tag_code VARCHAR(64) NOT NULL COMMENT 'CTN_POST_TAG.tag_code 标签编码',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CTN_POST_TAG.create_time 创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'CTN_POST_TAG.update_time 更新时间',
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'CTN_POST_TAG.deleted_flag 删除标记',
    version_num INT NOT NULL DEFAULT 0 COMMENT 'CTN_POST_TAG.version_num 版本号',
    CONSTRAINT PK_CTN_POST_TAG PRIMARY KEY (id),
    CONSTRAINT AK_CTN_POST_TAG_1 UNIQUE (post_id, tag_code),
    KEY IX_CTN_POST_TAG_1 (post_id),
    KEY IX_CTN_POST_TAG_2 (tag_code),
    CONSTRAINT FK_CTN_POST_TAG_1 FOREIGN KEY (post_id) REFERENCES CTN_POST(id)
) COMMENT='帖子标签映射表';

CREATE TABLE IF NOT EXISTS CTN_POST_CATEGORY_POLICY (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'CTN_POST_CATEGORY_POLICY.id 自增长ID',
    category_code VARCHAR(64) NOT NULL COMMENT 'CTN_POST_CATEGORY_POLICY.category_code 分类编码',
    enabled_flag TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'CTN_POST_CATEGORY_POLICY.enabled_flag 是否启用策略',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CTN_POST_CATEGORY_POLICY.create_time 创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'CTN_POST_CATEGORY_POLICY.update_time 更新时间',
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'CTN_POST_CATEGORY_POLICY.deleted_flag 删除标记',
    version_num INT NOT NULL DEFAULT 0 COMMENT 'CTN_POST_CATEGORY_POLICY.version_num 版本号',
    CONSTRAINT PK_CTN_POST_CATEGORY_POLICY PRIMARY KEY (id),
    CONSTRAINT AK_CTN_POST_CATEGORY_POLICY_1 UNIQUE (category_code)
) COMMENT='帖子分类访问策略表';

CREATE TABLE IF NOT EXISTS CTN_POST_CATEGORY_POLICY_GROUP (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'CTN_POST_CATEGORY_POLICY_GROUP.id 自增长ID',
    category_code VARCHAR(64) NOT NULL COMMENT 'CTN_POST_CATEGORY_POLICY_GROUP.category_code 分类编码',
    group_code VARCHAR(32) NOT NULL COMMENT 'CTN_POST_CATEGORY_POLICY_GROUP.group_code 分组编码',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CTN_POST_CATEGORY_POLICY_GROUP.create_time 创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'CTN_POST_CATEGORY_POLICY_GROUP.update_time 更新时间',
    deleted_flag TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'CTN_POST_CATEGORY_POLICY_GROUP.deleted_flag 删除标记',
    version_num INT NOT NULL DEFAULT 0 COMMENT 'CTN_POST_CATEGORY_POLICY_GROUP.version_num 版本号',
    CONSTRAINT PK_CTN_POST_CATEGORY_POLICY_GROUP PRIMARY KEY (id),
    CONSTRAINT AK_CTN_POST_CATEGORY_POLICY_GROUP_1 UNIQUE (category_code, group_code),
    KEY IX_CTN_POST_CATEGORY_POLICY_GROUP_1 (category_code),
    KEY IX_CTN_POST_CATEGORY_POLICY_GROUP_2 (group_code),
    CONSTRAINT FK_CTN_POST_CATEGORY_POLICY_GROUP_1
        FOREIGN KEY (category_code) REFERENCES CTN_POST_CATEGORY_POLICY(category_code)
) COMMENT='帖子分类访问策略分组映射表';

INSERT INTO USR_GROUP_PERMISSION (group_code, permission_code)
VALUES
    ('ADMIN', 'blog.post.write'),
    ('ADMIN', 'blog.post.publish'),
    ('FRIEND', 'blog.post.write'),
    ('FRIEND', 'blog.post.publish'),
    ('INTERVIEWER', 'blog.post.write'),
    ('INTERVIEWER', 'blog.post.publish')
ON DUPLICATE KEY UPDATE
    update_time = CURRENT_TIMESTAMP;

INSERT INTO CTN_POST_CATEGORY_POLICY (category_code, enabled_flag)
VALUES ('game', 1)
ON DUPLICATE KEY UPDATE
    enabled_flag = VALUES(enabled_flag),
    update_time = CURRENT_TIMESTAMP;

INSERT INTO CTN_POST_CATEGORY_POLICY_GROUP (category_code, group_code)
VALUES
    ('game', 'USER'),
    ('game', 'FRIEND'),
    ('game', 'ADMIN')
ON DUPLICATE KEY UPDATE
    update_time = CURRENT_TIMESTAMP;
