ALTER TABLE MDA_WALLPAPER_IMPORT_JOB
    ADD COLUMN progress_stage VARCHAR(32) NOT NULL DEFAULT 'QUEUED' AFTER status_text,
    ADD COLUMN progress_percent TINYINT UNSIGNED NOT NULL DEFAULT 5 AFTER progress_stage;
