server:
  port: 8084

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/shizuki_ai?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 12
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

shizuki:
  ai:
    quota:
      code: ai_round_total
      default-total-rounds: 5
  user:
    service-uri: ${USER_SERVICE_URI:http://localhost:8081}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
