CREATE TABLE IF NOT EXISTS CTN_LA_BAL_SOURCE_ACCOUNT (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_code VARCHAR(32) NOT NULL,
    status_code VARCHAR(32) NOT NULL DEFAULT 'UNBOUND',
    target_account_id BIGINT,
    nightly_enabled_flag SMALLINT NOT NULL DEFAULT 0,
    last_verified_datetime TIMESTAMP,
    last_synced_datetime TIMESTAMP,
    last_sync_status_code VARCHAR(32),
    last_sync_error_text VARCHAR(1024),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version_num INT NOT NULL DEFAULT 0,
    CONSTRAINT AK_CTN_LA_BAL_SOURCE_ACCOUNT_1 UNIQUE (user_id, provider_code)
);

CREATE INDEX IF NOT EXISTS IX_CTN_LA_BAL_SOURCE_ACCOUNT_1
    ON CTN_LA_BAL_SOURCE_ACCOUNT (user_id, provider_code, status_code);

CREATE INDEX IF NOT EXISTS IX_CTN_LA_BAL_SOURCE_ACCOUNT_2
    ON CTN_LA_BAL_SOURCE_ACCOUNT (user_id, nightly_enabled_flag, status_code);

CREATE TABLE IF NOT EXISTS CTN_LA_BAL_BIND_SESSION (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_code VARCHAR(32) NOT NULL,
    target_account_id BIGINT,
    session_code VARCHAR(64) NOT NULL,
    status_code VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    qr_code_payload_text TEXT,
    qr_code_image_url_text TEXT,
    login_url_text VARCHAR(512),
    expires_datetime TIMESTAMP NOT NULL,
    completed_datetime TIMESTAMP,
    failure_reason_text VARCHAR(1024),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version_num INT NOT NULL DEFAULT 0,
    CONSTRAINT AK_CTN_LA_BAL_BIND_SESSION_1 UNIQUE (session_code)
);

CREATE INDEX IF NOT EXISTS IX_CTN_LA_BAL_BIND_SESSION_1
    ON CTN_LA_BAL_BIND_SESSION (user_id, provider_code, status_code, create_time);

CREATE TABLE IF NOT EXISTS CTN_LA_BAL_IMPORT_JOB (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_code VARCHAR(32) NOT NULL,
    source_account_id BIGINT,
    target_account_id BIGINT,
    trigger_type VARCHAR(32) NOT NULL,
    status_code VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    imported_count INT NOT NULL DEFAULT 0,
    duplicate_count INT NOT NULL DEFAULT 0,
    skipped_count INT NOT NULL DEFAULT 0,
    error_text VARCHAR(1024),
    raw_file_path_text TEXT,
    request_from_datetime TIMESTAMP,
    request_to_datetime TIMESTAMP,
    started_datetime TIMESTAMP,
    finished_datetime TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version_num INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS IX_CTN_LA_BAL_IMPORT_JOB_1
    ON CTN_LA_BAL_IMPORT_JOB (user_id, provider_code, status_code, create_time);

CREATE INDEX IF NOT EXISTS IX_CTN_LA_BAL_IMPORT_JOB_2
    ON CTN_LA_BAL_IMPORT_JOB (source_account_id, create_time);

CREATE TABLE IF NOT EXISTS CTN_LA_BAL_IMPORT_MAPPING (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_code VARCHAR(32) NOT NULL,
    source_account_id BIGINT,
    import_job_id BIGINT,
    transaction_id BIGINT,
    external_id VARCHAR(128),
    digest_code VARCHAR(128) NOT NULL,
    occurred_datetime TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version_num INT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS AK_CTN_LA_BAL_IMPORT_MAPPING_1
    ON CTN_LA_BAL_IMPORT_MAPPING (user_id, provider_code, digest_code);

CREATE UNIQUE INDEX IF NOT EXISTS AK_CTN_LA_BAL_IMPORT_MAPPING_2
    ON CTN_LA_BAL_IMPORT_MAPPING (user_id, provider_code, external_id)
    WHERE external_id IS NOT NULL AND external_id <> '';

CREATE INDEX IF NOT EXISTS IX_CTN_LA_BAL_IMPORT_MAPPING_1
    ON CTN_LA_BAL_IMPORT_MAPPING (source_account_id, import_job_id, create_time);
