CREATE TABLE IF NOT EXISTS MEGURI_PROMPT_CACHE_METRICS (
    id BIGSERIAL PRIMARY KEY,
    source_id VARCHAR(80) NOT NULL UNIQUE,
    observed_at VARCHAR(48) NOT NULL,
    received_at TIMESTAMP NOT NULL,
    payload_json TEXT NOT NULL,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP NOT NULL,
    deleted_flag INTEGER NOT NULL DEFAULT 0,
    version_num INTEGER NOT NULL DEFAULT 0
);
