CREATE TABLE IF NOT EXISTS MDA_AMBIENT_SOURCE_ASSET (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider_code VARCHAR(32) NOT NULL,
    source_sound_id VARCHAR(64) NOT NULL,
    asset_id BIGINT NULL REFERENCES MDA_ASSET(id),
    import_status VARCHAR(16) NOT NULL DEFAULT 'IMPORTING',
    title_text VARCHAR(256) NOT NULL DEFAULT '',
    author_text VARCHAR(256) NOT NULL DEFAULT '',
    license_code VARCHAR(32) NOT NULL DEFAULT '',
    license_name VARCHAR(128) NOT NULL DEFAULT '',
    source_page_url VARCHAR(1024) NOT NULL DEFAULT '',
    duration_value DOUBLE PRECISION NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version_num INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT AK_MDA_AMBIENT_SOURCE_ASSET_1 UNIQUE (user_id, provider_code, source_sound_id),
    CONSTRAINT AK_MDA_AMBIENT_SOURCE_ASSET_2 UNIQUE (asset_id)
);

CREATE INDEX IF NOT EXISTS IX_MDA_AMBIENT_SOURCE_ASSET_1
    ON MDA_AMBIENT_SOURCE_ASSET (user_id, import_status);
