ALTER TABLE MDA_WALLPAPER_IMPORT_JOB
    ADD COLUMN progress_stage VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    ADD COLUMN progress_percent SMALLINT NOT NULL DEFAULT 5,
    ADD CONSTRAINT CK_MDA_WALLPAPER_IMPORT_JOB_PROGRESS_PERCENT
        CHECK (progress_percent BETWEEN 0 AND 100);
