$ErrorActionPreference = 'Stop'

$preferredName = '钱迹'
$fallbackAppId = 'Microsoft.AutoGenerated.{AD92FD22-9A0C-A79B-ED62-21A95ABF84F8}'
$logDir = 'D:\program\shizuki-site\data\qianji-sync\logs'
$logFile = Join-Path $logDir 'qianji-app-launch.log'

function Resolve-QianjiAppId {
  $app = Get-StartApps | Where-Object { $_.Name -eq $preferredName } | Select-Object -First 1
  if ($app -and $app.AppID) {
    return [string]$app.AppID
  }
  return $fallbackAppId
}

New-Item -ItemType Directory -Force -Path $logDir | Out-Null

$appId = Resolve-QianjiAppId
if (-not $appId) {
  throw '[qianji-app] Unable to resolve Qianji AppID'
}

$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
"[$timestamp] launching qianji app id=$appId" | Out-File -FilePath $logFile -Encoding utf8 -Append

Start-Process explorer.exe "shell:AppsFolder\$appId"
