server:
  port: 8080

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s

shizuki:
  gateway:
    auth:
      enabled: true
      user-service-introspect-url: ${USER_SERVICE_URI:http://localhost:8081}/api/v1/auth/introspect
      public-paths:
        - /api/v1/auth/tokens
        - /api/v1/auth/register/**
        - /api/v1/auth/oauth/**
        - /api/v1/auth/bindings/**
        - /api/v1/auth/captchas/**
        - /api/v1/auth/verifications/**
        - /actuator/**
    guest-paths:
      - /api/v1/posts/**
      - /api/v1/apps/**
      - /api/v1/ai-sessions/**
      - /api/v1/assets/public/**
      - /api/v1/assets/*/download-url
