server:
  port: 8083

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/shizuki_media?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 12
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

shizuki:
  internal:
    auth:
      # Use encrypted value from Nacos, e.g. ENC(...)
      shared-secret: ${INTERNAL_AUTH_SHARED_SECRET:}
      clock-skew-seconds: ${INTERNAL_AUTH_CLOCK_SKEW_SECONDS:300}
      nonce-ttl-seconds: ${INTERNAL_AUTH_NONCE_TTL_SECONDS:300}
  music:
    spotify:
      # Use encrypted value from Nacos, e.g. ENC(...)
      client-id: ${SPOTIFY_CLIENT_ID:}
      # Use encrypted value from Nacos, e.g. ENC(...)
      client-secret: ${SPOTIFY_CLIENT_SECRET:}
      token-url: ${SPOTIFY_TOKEN_URL:https://accounts.spotify.com/api/token}
      search-url: ${SPOTIFY_SEARCH_URL:https://api.spotify.com/v1/search}
      track-url: ${SPOTIFY_TRACK_URL:https://api.spotify.com/v1/tracks}
      connect-timeout-ms: ${SPOTIFY_CONNECT_TIMEOUT_MS:800}
      read-timeout-ms: ${SPOTIFY_READ_TIMEOUT_MS:1500}
      retry-count: ${SPOTIFY_RETRY_COUNT:2}
      retry-backoff-ms: ${SPOTIFY_RETRY_BACKOFF_MS:80}
      retry-max-backoff-ms: ${SPOTIFY_RETRY_MAX_BACKOFF_MS:600}
      circuit-breaker-failure-threshold: ${SPOTIFY_CB_FAILURE_THRESHOLD:3}
      circuit-breaker-open-seconds: ${SPOTIFY_CB_OPEN_SECONDS:30}
  user:
    service-uri: ${USER_SERVICE_URI:http://localhost:8081}
    timeout-ms: ${USER_SERVICE_TIMEOUT_MS:1200}
  media:
    storage:
      private-bucket: ${OSS_PRIVATE_BUCKET:shizuki-private}
      public-bucket: ${OSS_PUBLIC_BUCKET:shizuki-public}
      public-base-url: ${OSS_PUBLIC_BASE_URL:}
      sign-expire-seconds: 600
      max-upload-size: 52428800
      max-l2d-zip-entry-count: 2048
      max-l2d-zip-entry-name-length: 1024
      max-l2d-zip-single-entry-size: 20971520
      max-l2d-zip-total-size: 104857600
      enable-object-hash-dedup: true
      enable-security-scan-hook: false
      allowed-content-types:
        - image/png
        - image/jpeg
        - image/webp
        - image/gif
        - image/apng
        - application/zip
        - application/x-zip-compressed
        - audio/mpeg
        - audio/wav
        - audio/ogg
  oss:
    endpoint: ${OSS_ENDPOINT:https://oss-cn-hangzhou.aliyuncs.com}
    # Use encrypted value from Nacos, e.g. ENC(...)
    access-key-id: ${OSS_ACCESS_KEY_ID:}
    # Use encrypted value from Nacos, e.g. ENC(...)
    access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
  security:
    secret:
      enforce: ${SECRET_ENFORCE:true}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
