server:
  port: 8083

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/shizuki_media?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 12
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

shizuki:
  media:
    storage:
      private-bucket: ${OSS_PRIVATE_BUCKET:shizuki-private}
      public-bucket: ${OSS_PUBLIC_BUCKET:shizuki-public}
      sign-expire-seconds: 600
      max-upload-size: 52428800
      allowed-content-types:
        - image/png
        - image/jpeg
        - image/webp
        - audio/mpeg
        - audio/wav
        - audio/ogg
  oss:
    endpoint: ${OSS_ENDPOINT:https://oss-cn-hangzhou.aliyuncs.com}
    # Use encrypted value from Nacos, e.g. ENC(...)
    access-key-id: ${OSS_ACCESS_KEY_ID:}
    # Use encrypted value from Nacos, e.g. ENC(...)
    access-key-secret: ${OSS_ACCESS_KEY_SECRET:}
  security:
    secret:
      enforce: ${SECRET_ENFORCE:true}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
