server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/shizuki_user?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 4
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

shizuki:
  oauth:
    github:
      # Use encrypted value from Nacos, e.g. ENC(...)
      client-id: ${GITHUB_CLIENT_ID:}
      # Use encrypted value from Nacos, e.g. ENC(...)
      client-secret: ${GITHUB_CLIENT_SECRET:}
      authorize-url: https://github.com/login/oauth/authorize
      token-url: https://github.com/login/oauth/access_token
      user-api-url: https://api.github.com/user
  security:
    secret:
      enforce: ${SECRET_ENFORCE:true}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
